name: Build and deploy to Azure Static Web Apps (ashy-coast-0f7701e10)

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup environment for pupeteer
        run: |
          sudo yum -y install libXScrnSaver-1.2.2-6.1.el7.x86_64
          sudo yum install -y chromium
          apt install chromium-browser
          apt install libxkbcommon0 
          apt install libxshmfence1
          apt install 1622  apt-get install ca-certificates 
          apt install fonts-liberation 
          apt install libasound2 
          apt install libatk-bridge2.0-0 
          apt install libatk1.0-0 
          apt install libc6 
          apt install libcairo2 
          apt install libcups2 
          apt install libdbus-1-3 
          apt install libexpat1 
          apt install libfontconfig1 
          apt install libgbm1 
          apt install libgcc1 
          apt install libglib2.0-0 
          apt install libgtk-3-0 
          apt install libnspr4 
          apt install libnss3 
          apt install libpango-1.0-0 
          apt install libpangocairo-1.0-0 
          apt install libstdc++6 
          apt install libx11-6 
          apt install libx11-xcb1 
          apt install libxcb1 
          apt install libxcomposite1 
          apt install libxcursor1 
          apt install libxdamage1 
          apt install libxext6 
          apt install libxfixes3 
          apt install libxi6 
          apt install libxrandr2 
          apt install libxrender1 
          apt install libxss1 
          apt install libxtst6 
          apt install lsb-release wget 
          apt install xdg-utils
          apt install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_COAST_0F7701E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          production_branch: 'main'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: 'yarn build'
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: './docs/.vitepress/dist' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_COAST_0F7701E10 }}
          action: 'close'
