name: Build and deploy to Azure Static Web Apps (ashy-coast-0f7701e10)

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    # container: ghcr.io/puppeteer/puppeteer:latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - run: 'npm install -g puppeteer --unsafe-perm=true'
      # - run: 'sudo apt-get install chromium-browser'
      # - run: 'sudo apt-get install libx11-xcb1 libxcomposite1 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6'
      - run: 'apt-get update && apt-get install -y --no-install-recommends libasound2=1.1.8-1 libatk-bridge2.0-0=2.30.0-5 libatk1.0-0=2.30.0-2 libatspi2.0-0=2.30.0-7 libc6=2.28-10+deb10u1 libcairo2=1.16.0-4+deb10u1 libcups2=2.2.10-6+deb10u5 libdbus-1-3=1.12.20-0+deb10u1 libdrm2=2.4.97-1 libexpat1=2.2.6-2+deb10u4 libgbm1=18.3.6-2+deb10u1 libgcc1=1:8.3.0-6 libglib2.0-0=2.58.3-2+deb10u3 libnspr4=2:4.20-1 libnss3=2:3.42.1-1+deb10u5 libpango-1.0-0=1.42.4-7~deb10u1 libpangocairo-1.0-0=1.42.4-7~deb10u1 libstdc++6=8.3.0-6 libuuid1=2.33.1-0.1 libx11-6=2:1.6.7-1+deb10u2 libx11-xcb1=2:1.6.7-1+deb10u2 libxcb-dri3-0=1.13.1-2 libxcb1=1.13.1-2 libxcomposite1=1:0.4.4-2 libxcursor1=1:1.1.15-2 libxdamage1=1:1.1.4-3+b3 libxext6=2:1.3.3-1+b2 libxfixes3=1:5.0.3-1 libxi6=2:1.7.9-1 libxkbcommon0=0.8.2-1 libxrandr2=2:1.5.1-1 libxrender1=1:0.9.10-1 libxshmfence1=1.3-1 libxss1=1:1.2.3-1 libxtst6=2:1.2.3-1 && apt-get clean && rm -rf /var/lib/apt/lists/*'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_COAST_0F7701E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          production_branch: 'main'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: 'yarn build'
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: './docs/.vitepress/dist' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_COAST_0F7701E10 }}
          action: 'close'
